name: clickbuy
description: "ClickBuy es una aplicación web mCommerce en Flutter, con autenticación de usuarios usando Firebase, listado de productos desde una API externa y carrito de compras persistente."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  animate_do: ^4.2.0
  card_swiper: ^3.0.1
  cloud_firestore: ^6.0.2
  dio: ^5.9.0
  easy_localization: ^3.0.8
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_riverpod: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  intl: ^0.20.2
  riverpod_annotation: ^3.0.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.0
  # riverpod_test: eliminar, no es compatible con Riverpod 3


flutter:
  uses-material-design: true
  assets:
    - assets/notfound/